#!/usr/bin/env python3
"""Small maintenance utilities for the second-brain markdown wiki."""

from __future__ import annotations

import argparse
import datetime as dt
import pathlib
import re
import sys
from collections import Counter, defaultdict


ROOT = pathlib.Path(__file__).resolve().parents[1]
WIKI_DIR = ROOT / "wiki"
RAW_DIR = ROOT / "raw"
INDEX_PATH = WIKI_DIR / "index.md"
LOG_PATH = WIKI_DIR / "log.md"

SECTION_ORDER = [
    ("overview", WIKI_DIR, [WIKI_DIR / "overview.md"]),
    ("sources", WIKI_DIR / "sources", None),
    ("entities", WIKI_DIR / "entities", None),
    ("concepts", WIKI_DIR / "concepts", None),
    ("analyses", WIKI_DIR / "analyses", None),
    ("syntheses", WIKI_DIR / "syntheses", None),
]

WIKILINK_RE = re.compile(r"\[\[([^\]|#]+)(?:#[^\]|]+)?(?:\|[^\]]+)?\]\]")
FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)


def wiki_markdown_files() -> list[pathlib.Path]:
    return sorted(
        path
        for path in WIKI_DIR.rglob("*.md")
        if path.name not in {"index.md", "log.md"}
        and "schema" not in path.relative_to(WIKI_DIR).parts
    )


def parse_frontmatter(text: str) -> dict[str, str]:
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}

    values: dict[str, str] = {}
    for raw_line in match.group(1).splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, value = line.split(":", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def strip_frontmatter(text: str) -> str:
    return FRONTMATTER_RE.sub("", text, count=1)


def first_paragraph(text: str) -> str:
    body = strip_frontmatter(text)
    lines = [line.rstrip() for line in body.splitlines()]
    paragraph: list[str] = []
    for line in lines:
        if not line.strip():
            if paragraph:
                break
            continue
        if line.startswith("#"):
            continue
        if line.startswith("- "):
            if paragraph:
                break
            continue
        paragraph.append(line.strip())
    return " ".join(paragraph).strip()


def page_title(path: pathlib.Path, text: str, frontmatter: dict[str, str]) -> str:
    if frontmatter.get("title"):
        return frontmatter["title"]
    for line in strip_frontmatter(text).splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem.replace("-", " ").title()


def page_type(path: pathlib.Path) -> str:
    if path.parent == WIKI_DIR:
        return "overview"
    return path.parent.name


def summary_for_page(text: str, frontmatter: dict[str, str]) -> tuple[str, str]:
    summary_en = frontmatter.get("summary_en") or frontmatter.get("summary")
    summary_zh = frontmatter.get("summary_zh", "")
    if summary_en or summary_zh:
        return summary_en or "", summary_zh
    paragraph = first_paragraph(text)
    if paragraph:
        return paragraph, ""
    return "No summary available yet.", ""


def load_pages() -> list[dict[str, object]]:
    pages = []
    for path in wiki_markdown_files():
        text = path.read_text(encoding="utf-8")
        frontmatter = parse_frontmatter(text)
        title = page_title(path, text, frontmatter)
        pages.append(
            {
                "path": path,
                "rel": path.relative_to(WIKI_DIR),
                "title": title,
                "type": page_type(path),
                "summary_en": summary_for_page(text, frontmatter)[0],
                "summary_zh": summary_for_page(text, frontmatter)[1],
                "text": text,
            }
        )
    return pages


def rebuild_index(_: argparse.Namespace) -> int:
    pages = load_pages()
    by_type: dict[str, list[dict[str, object]]] = defaultdict(list)
    for page in pages:
        by_type[str(page["type"])].append(page)

    title_map = {
        "overview": ("Overview", "总览"),
        "sources": ("Sources", "来源"),
        "entities": ("Entities", "实体"),
        "concepts": ("Concepts", "概念"),
        "analyses": ("Analyses", "分析"),
        "syntheses": ("Syntheses", "综合"),
    }

    lines = [
        "# Wiki Index",
        "",
        "知识库索引",
        "",
        "This file is generated by `/root/.openclaw/.venv/bin/python scripts/wiki_tools.py rebuild-index`.",
        "此文件由 `/root/.openclaw/.venv/bin/python scripts/wiki_tools.py rebuild-index` 自动生成。",
        "",
    ]

    for section_key, _, fixed_paths in SECTION_ORDER:
        section_en, section_zh = title_map[section_key]
        lines.append(f"## {section_en}")
        lines.append("")
        lines.append(f"_{section_zh}_")
        lines.append("")
        items = []
        if fixed_paths is not None:
            fixed_set = {path.resolve() for path in fixed_paths}
            items = [page for page in pages if pathlib.Path(page["path"]).resolve() in fixed_set]
        else:
            items = by_type.get(section_key, [])

        if not items:
            lines.append("_No pages yet._")
            lines.append("_暂无页面。_")
            lines.append("")
            continue

        for page in sorted(items, key=lambda item: str(item["title"]).lower()):
            rel = pathlib.Path(page["rel"]).as_posix()
            title = str(page["title"])
            summary_en = str(page["summary_en"])
            summary_zh = str(page["summary_zh"])
            lines.append(f"- [{title}]({rel})")
            if summary_en:
                lines.append(f"  {summary_en}")
            if summary_zh:
                lines.append(f"  {summary_zh}")
        lines.append("")

    INDEX_PATH.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Rebuilt {INDEX_PATH.relative_to(ROOT)}")
    return 0


def append_log(kind: str, title: str, details: str | None) -> None:
    today = dt.date.today().isoformat()
    entry_lines = ["", f"## [{today}] {kind.upper()} | {title}", ""]
    if details:
        for line in details.splitlines():
            stripped = line.strip()
            if stripped:
                entry_lines.append(f"- {stripped}")
    else:
        entry_lines.append("- No details provided.")
    with LOG_PATH.open("a", encoding="utf-8") as handle:
        handle.write("\n".join(entry_lines) + "\n")


def log_command(args: argparse.Namespace) -> int:
    append_log(args.kind, args.title, args.details)
    print(f"Appended log entry to {LOG_PATH.relative_to(ROOT)}")
    return 0


def register_source(args: argparse.Namespace) -> int:
    source_path = pathlib.Path(args.path)
    if not source_path.is_absolute():
        source_path = ROOT / source_path
    if not source_path.exists():
        print(f"Source not found: {source_path}", file=sys.stderr)
        return 1

    title = args.title or source_path.stem.replace("-", " ").replace("_", " ").title()
    details = f"Registered raw source `{source_path.relative_to(ROOT)}`."
    append_log("ingest", title, details)
    print(f"Registered source in {LOG_PATH.relative_to(ROOT)}")
    return 0


def extract_wikilinks(text: str) -> list[str]:
    return [match.group(1).strip() for match in WIKILINK_RE.finditer(text)]


def lint(_: argparse.Namespace) -> int:
    pages = load_pages()
    title_to_page = {str(page["title"]): page for page in pages}
    inbound = Counter()
    broken_links: list[tuple[str, str]] = []

    for page in pages:
        page_title_value = str(page["title"])
        for target in extract_wikilinks(str(page["text"])):
            if target in title_to_page:
                inbound[target] += 1
            else:
                broken_links.append((page_title_value, target))

    orphan_pages = [
        str(page["title"])
        for page in pages
        if str(page["title"]) != "Overview" and inbound[str(page["title"])] == 0
    ]

    source_roots = [RAW_DIR / "inbox", RAW_DIR / "processed"]
    raw_sources = sorted(
        path
        for root in source_roots
        for path in root.rglob("*")
        if path.is_file() and path.name != ".gitkeep"
    )
    source_text = "\n".join(str(page["text"]) for page in pages if page["type"] == "sources")
    uncatalogued_sources = [
        path.relative_to(ROOT).as_posix()
        for path in raw_sources
        if path.relative_to(ROOT).as_posix() not in source_text
    ]

    print("Lint report")
    print("===========")
    print(f"Wiki pages: {len(pages)}")
    print(f"Broken wikilinks: {len(broken_links)}")
    for source_title, target in broken_links:
        print(f"- broken link from '{source_title}' to '[[{target}]]'")

    print(f"Orphan pages: {len(orphan_pages)}")
    for title in orphan_pages:
        print(f"- orphan page '{title}'")

    print(f"Raw sources without mention in source notes: {len(uncatalogued_sources)}")
    for rel in uncatalogued_sources:
        print(f"- untracked source '{rel}'")

    return 1 if broken_links or uncatalogued_sources else 0


def search(args: argparse.Namespace) -> int:
    query_terms = [term.lower() for term in re.findall(r"\w+", " ".join(args.query))]
    if not query_terms:
        print("Please provide at least one search term.", file=sys.stderr)
        return 1

    pages = load_pages()
    scored = []
    for page in pages:
        haystack = " ".join(
            [
                str(page["title"]),
                str(page["summary_en"]),
                str(page["summary_zh"]),
                str(page["text"]),
            ]
        ).lower()
        score = sum(haystack.count(term) for term in query_terms)
        if score:
            scored.append((score, page))

    scored.sort(key=lambda item: (-item[0], str(item[1]["title"]).lower()))
    for score, page in scored[: args.limit]:
        rel = pathlib.Path(page["rel"]).as_posix()
        print(f"[{score}] {page['title']} - {rel}")
        summary_en = str(page["summary_en"])
        summary_zh = str(page["summary_zh"])
        if summary_zh:
            print(f"    {summary_en}")
            print(f"    {summary_zh}")
        else:
            print(f"    {summary_en}")

    if not scored:
        print("No matches found.")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    rebuild_parser = subparsers.add_parser("rebuild-index", help="Rebuild wiki/index.md")
    rebuild_parser.set_defaults(func=rebuild_index)

    lint_parser = subparsers.add_parser("lint", help="Run a wiki health check")
    lint_parser.set_defaults(func=lint)

    search_parser = subparsers.add_parser("search", help="Search wiki markdown content")
    search_parser.add_argument("query", nargs="+", help="Search terms")
    search_parser.add_argument("--limit", type=int, default=10, help="Max results")
    search_parser.set_defaults(func=search)

    log_parser = subparsers.add_parser("log", help="Append an entry to wiki/log.md")
    log_parser.add_argument("kind", choices=["ingest", "query", "lint", "note", "bootstrap"])
    log_parser.add_argument("title", help="Short entry title")
    log_parser.add_argument("--details", help="Bullet details for the log entry")
    log_parser.set_defaults(func=log_command)

    register_parser = subparsers.add_parser(
        "register-source",
        help="Record a raw source in the wiki log",
    )
    register_parser.add_argument("path", help="Path to a raw source file")
    register_parser.add_argument("--title", help="Optional human-readable title")
    register_parser.set_defaults(func=register_source)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
